name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
          turnip_workdir/turnip_${{ steps.versions3.outputs.tag }}.zip
    
    - id: versions1
      run: echo "description=$(cat turnip_workdir/description)" >> "$GITHUB_OUTPUT"
    - id: versions2
      run: echo "name=$(cat turnip_workdir/release)" >> "$GITHUB_OUTPUT"
    - id: versions3
      run: echo "tag=$(cat turnip_workdir/tag)" >> "$GITHUB_OUTPUT"
      
    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.versions1.outputs.description }} 
        tag_name: ${{ steps.versions3.outputs.tag }}
        name: ${{ steps.versions2.outputs.name }}
        files: |
           turnip_workdir/turnip_${{ steps.versions3.outputs.tag }}.zip
